version: "2"
services:
    pvit-web:
        restart: always
        build: .
        ports: 
            - "1629:3000"
        links:
            - pvitredis
    pvitredis:
        restart: always
        image: redis
